In [ ]:

Student Name: Tulika Singh
Student ID: BDAP-10150105
Student Email: tulika.bdapm10150105@spjain.org
Student GitHub Repo URL:https://github.com/TS19


Q.1 Create a redis list with value [10, 20, 30]

Ans.1
redis 127.0.0.1:6379> LPUSH list1 10                        
# Create a list with first value 10
(integer) 1
redis 127.0.0.1:6379> RPUSH list1 20                        
# Create a list with second value 20
(integer) 2
redis 127.0.0.1:6379> RPUSH list1 30                       
 # Create a list with third value 30
(integer) 3
redis 127.0.0.1:6379> LRANGE list1 0 10                     
# Display all values of the list
1) "10"
2) "20"
3) "30"

Q.2 Change the list to [20, 20, 20]

Ans.2 
redis 127.0.0.1:6379> LSET list1 0 20                      
 # Will set the first value as 20
OK
redis 127.0.0.1:6379> LSET list1 1 20                      
 # Will set the second value as 20
OK
redis 127.0.0.1:6379> LSET list1 2 20                       
# Will set the third value as 20
OK
redis 127.0.0.1:6379> LRANGE list1 0 20                     
# Display all values of the list
1) "20"
2) "20"
3) "20"

Q.3 Create a sorted set with the value {1, 2, 3 }

Ans.3
redis 127.0.0.1:6379> ZADD myset1 1 "one" 2 "two" 3 "three"     
#Create a sorted set with values {1,2,3}

(integer) 3
redis 127.0.0.1:6379> ZRANGE myset1 0 -1 withscores       
 # Display all values of the sorted set
1) "one"
2) "1"
3) "two"
4) "2"
5) "three"
6) "3"

Q.4 Add  {3, 4, -5} to this set
redis 127.0.0.1:6379> ZADD myset1 3 "tri" 4 "four" -5 "mfive"
(integer) 2
redis 127.0.0.1:6379> zrange myset1 0 -1 withscores
 1) "mfive"
 2) "-5"
 3) "one"
 4) "1"
 5) "two"
 6) "2"
 7) "three"
 8) "3"
 9) "tri"
10) "3"
11) "four"
12) "4"

Q.5 Display the list contents and the ordered set contents
Ans.5
redis 127.0.0.1:6379> LRANGE list1 0 20                     # Display all values of the list
1) "20"
2) "20"
3) "20"
redis 127.0.0.1:6379> zrange myset1 0 -1 withscores
 1) "mfive"
 2) "-5"
 3) "one"
 4) "1"
 5) "two"
 6) "2"
 7) "three"
 8) "3"
 9) "tri"
10) "3"
11) "four"
12) "4"